# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v0.2.1; do not edit.
class Preso < Formula
  desc "Native markdown presentations"
  homepage "https://github.com/camjjack/preso"
  version "0.2.1"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "https://github.com/camjjack/preso/releases/download/v0.2.1/preso-v0.2.1-aarch64-apple-darwin.tar.gz"
    sha256 "fdd18d9ef78306509ad39de7be54147ad9fdbf2e489f61cdd3c2f6e0b1034189"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "https://github.com/camjjack/preso/releases/download/v0.2.1/preso-v0.2.1-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "844ac40326c01c1458a1357d3bb822a9d4465a0fdc47acea1013ab342c01e896"

    depends_on arch: :x86_64
  end

  conflicts_with "preso-video", because: "both install a `preso` binary"

  def install
    bin.install "preso"
    bin.install "preso-convert"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
