# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v0.1.0; do not edit.
#
# The --features video build: plays <!-- video: … --> clips inline on the
# slide. Links GStreamer dynamically, so it depends on the gstreamer
# formula (the monorepo build: base/good/bad/ugly/libav plugins included).
class PresoVideo < Formula
  desc "Native markdown presentations (inline video via GStreamer)"
  homepage "https://github.com/camjjack/preso"
  version "0.1.0"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "https://github.com/camjjack/preso/releases/download/v0.1.0/preso-v0.1.0-aarch64-apple-darwin-video.tar.gz"
    sha256 "022866d63e949dd9bf2c744a0840b2f5dddf4a0cb8cb74a1e47c56e620c397bb"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "https://github.com/camjjack/preso/releases/download/v0.1.0/preso-v0.1.0-x86_64-unknown-linux-gnu-video.tar.gz"
    sha256 "c2c399303826a1aac12b5a386f098a3d37a4eeb6ca35a1215b9d35bb58196ecf"

    depends_on arch: :x86_64
    depends_on "patchelf" => :build
  end

  depends_on "gstreamer"

  conflicts_with "preso", because: "both install a `preso` binary"

  def install
    bin.install "preso"
    if OS.mac?
      # The release binary links GStreamer through upstream's
      # @rpath/libgst*.dylib install names but ships no LC_RPATH of its
      # own; point it at brew's GStreamer. Editing load commands
      # invalidates the ad-hoc signature on Apple Silicon, so re-sign.
      system "install_name_tool", "-add_rpath",
             Formula["gstreamer"].opt_lib.to_s, bin/"preso"
      system "codesign", "--force", "--sign", "-", bin/"preso"
    else
      # Linuxbrew's GStreamer lives outside the default loader paths.
      system "patchelf", "--add-rpath", HOMEBREW_PREFIX/"lib", bin/"preso"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
