# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v0.2.0; do not edit.
class Preso < Formula
  desc "Native markdown presentations"
  homepage "https://github.com/camjjack/preso"
  version "0.2.0"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "https://github.com/camjjack/preso/releases/download/v0.2.0/preso-v0.2.0-aarch64-apple-darwin.tar.gz"
    sha256 "2bfc507e9a8ebaf1aca2b6bca1d5e93530c0611b5a9e3a473a21bfd497f0f096"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "https://github.com/camjjack/preso/releases/download/v0.2.0/preso-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "e8bb423214372bc44b8a8857ffbaecbadf5fb283df1611c334b109fd4d1029d4"

    depends_on arch: :x86_64
  end

  conflicts_with "preso-video", because: "both install a `preso` binary"

  def install
    bin.install "preso"
    bin.install "preso-convert"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
