# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v0.2.2; do not edit.
class Preso < Formula
  desc "Native markdown presentations"
  homepage "https://github.com/camjjack/preso"
  version "0.2.2"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "https://github.com/camjjack/preso/releases/download/v0.2.2/preso-v0.2.2-aarch64-apple-darwin.tar.gz"
    sha256 "cf7cbf00e4933df5c5b2cfe7f98e87772941c7a67b2f7cc64af2886c31816dc4"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "https://github.com/camjjack/preso/releases/download/v0.2.2/preso-v0.2.2-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "6ac06f41df63a3141db1ee682dc80ce327b2eff62e55c40b2df812717a04e928"

    depends_on arch: :x86_64
  end

  conflicts_with "preso-video", because: "both install a `preso` binary"

  def install
    bin.install "preso"
    bin.install "preso-convert"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
