# frozen_string_literal: true

# Generated by scripts/gen-homebrew-formulae.sh for v0.2.1; do not edit.
#
# The --features video build: plays <!-- video: … --> clips inline on the
# slide. Links GStreamer dynamically, so it depends on the gstreamer
# formula (the monorepo build: base/good/bad/ugly/libav plugins included).
class PresoVideo < Formula
  desc "Native markdown presentations (inline video via GStreamer)"
  homepage "https://github.com/camjjack/preso"
  version "0.2.1"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac?
    url "https://github.com/camjjack/preso/releases/download/v0.2.1/preso-v0.2.1-aarch64-apple-darwin-video.tar.gz"
    sha256 "63704a5d4717ff13429af43fcdccb4b482b14dbe9b8d3a1ee5d899369385b5a4"

    depends_on arch: :arm64
  end

  if OS.linux?
    url "https://github.com/camjjack/preso/releases/download/v0.2.1/preso-v0.2.1-x86_64-unknown-linux-gnu-video.tar.gz"
    sha256 "cd7006b76cae0b931c76ae9a39cb49a96e7f4b4285f8484fc275cb6f1c992c8c"

    depends_on arch: :x86_64
    depends_on "patchelf" => :build
  end

  depends_on "gstreamer"
  # GStreamer pulls these in, but their dylibs live in their own kegs and
  # the binary references them by @rpath, so each needs an rpath below.
  depends_on "glib"    # libgobject-2.0, libglib-2.0, libgio-2.0
  depends_on "gettext" # libintl.8 (keg-only, not in HOMEBREW_PREFIX/lib)

  conflicts_with "preso", because: "both install a `preso` binary"

  def install
    bin.install "preso"
    if OS.mac?
      # The release binary links GStreamer (and its glib/gettext deps)
      # through upstream's @rpath/lib*.dylib install names but ships no
      # LC_RPATH of its own. The libraries are split across kegs —
      # libgst*.dylib in gstreamer, libgobject/libglib/libgio in glib,
      # libintl in gettext — so add an rpath for each. Editing load
      # commands invalidates the ad-hoc signature on Apple Silicon, so
      # re-sign afterwards.
      ["gstreamer", "glib", "gettext"].each do |dep|
        system "install_name_tool", "-add_rpath",
               Formula[dep].opt_lib.to_s, bin/"preso"
      end
      system "codesign", "--force", "--sign", "-", bin/"preso"
    else
      # Linuxbrew's GStreamer lives outside the default loader paths.
      system "patchelf", "--add-rpath", HOMEBREW_PREFIX/"lib", bin/"preso"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/preso --version")
  end
end
